#!/bin/sh
# Hook installed by jammer-cli

output=$(jammer 2>&1)
jammer_exit_code=$?

if [ $jammer_exit_code -eq 127 ]; then
  echo "Warning: 'jammer' command not found, skipping pre-commit check."
  exit 0
elif [ $jammer_exit_code -ne 0 ]; then
  echo "$output"
  exit $jammer_exit_code
else
  exit 0
fi
