#!/bin/sh

# Pre-commit hook to check for keywords using jammer-cli

# Get the project root directory
PROJECT_ROOT=$(git rev-parse --show-toplevel)

# Run the jammer script before committing
ruby "$PROJECT_ROOT/bin/jammer"

# Exit with the status code from the jammer script
exit $? 