name: Release Gem

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Build and Publish Gem
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3"
        bundler-cache: true

    - name: Run RSpec tests
      run: bundle exec rspec

    - name: Run Rubocop
      run: bundle exec rubocop --display-cop-names

    - name: Build gem
      run: gem build jammer-cli.gemspec

    - name: Publish gem
      env:
        GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      run: gem push jammer-cli-*.gem
